package com.restaurant.backend.config;

import com.restaurant.backend.Entity.Booking;
import com.restaurant.backend.Entity.RestaurantTable;
import com.restaurant.backend.Entity.Zone;
import com.restaurant.backend.repository.BookingRepository;
import com.restaurant.backend.repository.TableRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

// NOTE: Seeding was generated by AI
/**
 * Seeds the database with demo tables and random bookings on application startup.
 * Only runs when the table table is empty to avoid duplicating data on restart.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final TableRepository tableRepository;
    private final BookingRepository bookingRepository;

    @Override
    public void run(String... args) {
        if (tableRepository.count() == 0) {
            log.info("Seeding tables...");
            List<RestaurantTable> tables = seedTables();
            log.info("Seeding random bookings...");
            seedBookings(tables);
            log.info("Seeding complete.");
        } else {
            log.info("Tables already present — skipping seed.");
        }
    }

    // -------------------------------------------------------------------------
    // Table layout
    // -------------------------------------------------------------------------
    //  MAIN HALL  (rows 0-1, cols 0-2)  — 6 tables
    //  WINDOW     (rows 0-1, cols 3-4)  — 4 tables
    //  PRIVATE    (row 3, cols 0-2)     — 3 tables
    //  PATIO      (row 5, cols 0-3)     — 4 tables
    // -------------------------------------------------------------------------

    private List<RestaurantTable> seedTables() {
        List<RestaurantTable> tables = new ArrayList<>();

        // ── Main Hall (6 tables) ──────────────────────────────────────────────
        tables.add(table("T1", 2, Zone.MAIN_HALL, false, 0, 0));
        tables.add(table("T2", 4, Zone.MAIN_HALL, false, 1, 0));
        tables.add(table("T3", 4, Zone.MAIN_HALL, true,  2, 0));  // accessible
        tables.add(table("T4", 6, Zone.MAIN_HALL, false, 0, 1));
        tables.add(table("T5", 2, Zone.MAIN_HALL, true,  1, 1));  // accessible
        tables.add(table("T6", 8, Zone.MAIN_HALL, false, 2, 1));

        // ── Window (4 tables) ────────────────────────────────────────────────
        tables.add(table("W1", 2, Zone.WINDOW, false, 3, 0));
        tables.add(table("W2", 4, Zone.WINDOW, false, 3, 1));
        tables.add(table("W3", 2, Zone.WINDOW, false, 4, 0));
        tables.add(table("W4", 4, Zone.WINDOW, false, 4, 1));

        // ── Private (3 tables) ───────────────────────────────────────────────
        tables.add(table("P1", 6, Zone.PRIVATE, true,  0, 3));  // accessible
        tables.add(table("P2", 8, Zone.PRIVATE, false, 1, 3));
        tables.add(table("P3", 4, Zone.PRIVATE, false, 2, 3));

        // ── Patio (4 tables) ─────────────────────────────────────────────────
        tables.add(table("O1", 2, Zone.PATIO, false, 0, 5));
        tables.add(table("O2", 4, Zone.PATIO, false, 1, 5));
        tables.add(table("O3", 6, Zone.PATIO, false, 2, 5));
        tables.add(table("O4", 4, Zone.PATIO, false, 3, 5));

        return tableRepository.saveAll(tables);
    }

    private RestaurantTable table(String label, int capacity, Zone zone,
                                   boolean accessible, int gridX, int gridY) {
        return RestaurantTable.builder()
                .label(label)
                .capacity(capacity)
                .zone(zone)
                .accessible(accessible)
                .gridX(gridX)
                .gridY(gridY)
                .build();
    }

    // -------------------------------------------------------------------------
    // Random bookings — ~20 spread across today and tomorrow
    // -------------------------------------------------------------------------

    private void seedBookings(List<RestaurantTable> tables) {
        ThreadLocalRandom rng = ThreadLocalRandom.current();
        LocalDate today    = LocalDate.now();
        LocalDate tomorrow = today.plusDays(1);

        List<Booking> bookings = new ArrayList<>();

        // Today: ~12 bookings
        bookings.addAll(generateBookingsForDate(tables, today, 12, rng));
        // Tomorrow: ~8 bookings
        bookings.addAll(generateBookingsForDate(tables, tomorrow, 8, rng));

        bookingRepository.saveAll(bookings);
    }

    private List<Booking> generateBookingsForDate(List<RestaurantTable> tables,
                                                   LocalDate date,
                                                   int count,
                                                   ThreadLocalRandom rng) {
        List<Booking> result = new ArrayList<>();

        // Opening hours: 11:00 – 21:00 in 30-min slots
        int[] startHalfHours = buildHalfHourSlots(11, 21);
        int[] durations      = {60, 90, 120, 150}; // minutes

        int attempts = 0;
        while (result.size() < count && attempts < count * 10) {
            attempts++;

            RestaurantTable table = tables.get(rng.nextInt(tables.size()));

            int startHalf    = startHalfHours[rng.nextInt(startHalfHours.length)];
            int durationMins = durations[rng.nextInt(durations.length)];

            LocalTime start = LocalTime.of(startHalf / 2, (startHalf % 2) * 30);
            LocalTime end   = start.plusMinutes(durationMins);

            // Don't go past midnight
            if (end.isAfter(LocalTime.of(23, 0))) continue;

            // Check for overlap with already-created bookings for this table+date
            boolean overlaps = result.stream()
                    .filter(b -> b.getTable().getId().equals(table.getId())
                              && b.getDate().equals(date))
                    .anyMatch(b -> start.isBefore(b.getEndTime())
                               && end.isAfter(b.getStartTime()));

            if (overlaps) continue;

            int groupSize = Math.max(1, Math.min(
                    table.getCapacity(),
                    rng.nextInt(1, table.getCapacity() + 1)
            ));

            result.add(Booking.builder()
                    .table(table)
                    .customerName(randomName(rng))
                    .groupSize(groupSize)
                    .date(date)
                    .startTime(start)
                    .endTime(end)
                    .build());
        }

        return result;
    }

    /** Half-hour slot indices from startHour (inclusive) to endHour (exclusive). */
    private int[] buildHalfHourSlots(int startHour, int endHour) {
        int total = (endHour - startHour) * 2;
        int[] slots = new int[total];
        for (int i = 0; i < total; i++) {
            slots[i] = startHour * 2 + i;
        }
        return slots;
    }

    private static final String[] NAMES = {
        "Alice Johnson", "Bob Smith", "Carol White", "David Brown", "Eva Davis",
        "Frank Miller", "Grace Wilson", "Henry Moore", "Ivy Taylor", "Jack Anderson",
        "Karen Thomas", "Liam Jackson", "Mia Harris", "Noah Martin", "Olivia Lee",
        "Paul Garcia", "Quinn Martinez", "Rachel Robinson", "Sam Clark", "Tina Lewis"
    };

    private String randomName(ThreadLocalRandom rng) {
        return NAMES[rng.nextInt(NAMES.length)];
    }
}

